name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  assistant:
    if: "!contains(github.event.comment.body, '@claude auto-review')"
    uses: tarosky/workflows/.github/workflows/claude-assistant.yml@main
    secrets: inherit
